apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: Deploy a FAILING app in ArgoCD
  annotations:
    description: Template to deploy ArgoCD app that FAILS
    tags: argocd,community,operator
    iconClass: icon-cassandra
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
objects:
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: ${APPLICATION_NAME}
    namespace: ${OPERATOR_NAMESPACE}
  spec:
    destination:
      namespace: ${OPERATOR_NAMESPACE}
      server: 'https://kubernetes.default.svc'
    project: default
    source:
      path: 'guestbook'
      targetRevision: HEAD
      repoURL: 'https://github.com/kubernetes/examples'
    syncPolicy:
      automated: 
        prune: true
        selfHeal: true
parameters:
- name: APPLICATION_NAME
  description: "The name of the application to deploy, which fails."
  required: false
  value: "app-fail"
- name: OPERATOR_NAMESPACE
  description: "The project where the operator will be installed."
  required: false
  value: "argocd"
